version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - "5432:5432"

  backend:
    image: arbitrage
    ports:
      - "8000:8000"

  backend2:
    image: arbitrage
    ports:
      - "8001:8000"

  backend3:
    image: arbitrage
    ports:
      - "8002:8000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
      - backend3
